version: '3.8'

services:

  admin-panel-module:
    container_name: admin-panel-module
    build:
      context: ./admin-panel-module
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
    networks:
      - app-network
    depends_on:
      - backend

  evaluate:
    container_name: evaluate
    build:
      context: ./evaluate/my-app
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    networks:
      - app-network
    depends_on:
      - backend

  feedback_agent:
    build:
      context: ./feedback-agent
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8001:8000"
    networks:
      - app-network

  backend:
    build:
      context: ./HRM-system-ZERNO-/backend
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - APP_URL=${APP_URL}
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
