"""Add waiter model

Revision ID: 1238e444e0bb
Revises: 2a0fed2ae92a
Create Date: 2024-11-21 16:11:17.010712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1238e444e0bb'
down_revision: Union[str, None] = '2a0fed2ae92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
